### ISSUE TITLE
"Control" key is always in "pressed" state

### ISSUE THREAD

**Issue by MasterGroosha** [nurdism/neko#1]
Hello, thank you for the Neko! I've successfully ran it on Scaleway server, however it seems that "Ctrl" key is always pressed. So that when I press "S", a "save as" dialog window is opened, "T" for new tab. And I cannot use numeric keys at all :(
How can I fix it?

Also I had to change "Version" in docker-compose file from "3.6" to "2.0" otherwise docker-compose throws an error. And I changed 2gb to 1gb, since I only have 1GB free RAM, the other 1GB is taken by other processes.

**Comment by nurdism** [comment]
I've had this happen occasionally, I've was able to kick it out by pressing the Ctrl key. I'll look into this a bit further and see if there's another solution.

**Comment by nurdism** [comment]
Try pressing the `alt` key too, if I alt-tab the browser it will tend to stick due to loosing focus when you alt tab.

**Comment by MasterGroosha** [comment]
Hmm.. somehow pressing "Ctrl" worked for me this time (I think I pressed it before with no luck). Thank you!
