### ISSUE TITLE
[BUG] adorable.io is down - might want to look at an alternative.

### ISSUE THREAD

**Issue by IngwiePhoenix** [nurdism/neko#109]
**Describe the bug**
While setting up reverse-proxying with NGINX, I used the dev tools to spot if there was anything I hadn't forwarded correctly. Whilst I got everything right, I noticed that `api.adorable.io` was refferenced - but visiting the domain gave me an error that the DNS name could not be looked up. That, as well as the link given on their Twitter page - both are not reachable.

**To Reproduce**
- Open the dev tools
- Log in
- You now have an error in your console! :)

**Expected behavior**
A cute avatar. Possibly a bird!

**Screenshots**
![image](https://user-images.githubusercontent.com/2893716/99869207-82559600-2bc9-11eb-99e3-49928d23cd98.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version ... latest? Shouldn't matter here anyway. o.o

**Additional context**
... None I could think of.

**Client Log:**
```
... See screenshots. ...
```

**Server Log:**
```
... client-side issue, no server logs needed. ...
```

**Comment by nurdism** [comment]
this is fixed in master, not released yet

**Comment by IngwiePhoenix** [comment]
Cool, thanks for letting me know! :)
