### ISSUE TITLE
What's the display name 

### ISSUE THREAD

**Issue by Zinedinarnaut** [nurdism/neko#127]

**Comment by Zinedinarnaut** [comment]
Idk what's the username is

**Comment by m1k1o** [comment]
> There are no accounts, display name (a.k.a. username) can be freely chosen. Only password needs to match. 

See this: https://github.com/m1k1o/neko#accounts

**Comment by Zinedinarnaut** [comment]
> > There are no accounts, display name (a.k.a. username) can be freely chosen. Only password needs to match.
> 
> See this: https://github.com/m1k1o/neko#accounts
