### ISSUE TITLE
Clipboard Synchronization

### ISSUE THREAD

**Issue by nurdism** [nurdism/neko#13]
Synchronize the clipboard between client and server. 

Client: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
Server: ?

**Comment by mikroskeem** [comment]
Perhaps `xsel` could be utilized?

**Comment by nurdism** [comment]
looks like its been done in go https://github.com/atotto/clipboard wondering if there is a way to do this with C

**Comment by nurdism** [comment]
added in https://github.com/nurdism/neko/commit/56a5dcf77f6a10445716485dc717acb901372561
