### ISSUE TITLE
Accessing from another PC

### ISSUE THREAD

**Issue by Okiesmokie** [nurdism/neko#17]
It works perfectly when accessing it from localhost, but when I try to access it from another PC on the network the state never changes from "checking" to "connected" - even after receiving the video and audio track.  Is there something I've configured incorrectly?

**Comment by nurdism** [comment]
I've updated the docker image, with the refactored code I've written over the last few days. Try pulling the new image and post the logs if this is still an issue.

**Comment by nurdism** [comment]
I believe this is related to #15 going to close this
