### ISSUE TITLE
Browser not loading

### ISSUE THREAD

**Issue by adecker794** [nurdism/neko#19]
I have installed neko, I was able to open it in Firefox, but once I am logged in, the browser does not pop up. I thought I had to install to firefox so I did that and still a black box, even after a reboot. Maybe I am missing something? I have the emojis and the chat, the settings in the top right are there. I am running on a ubuntu-server 16.04 VM.

**Comment by nurdism** [comment]
dupe of #14

**Comment by esinanturan** [comment]
I am having the same issue, application starts but it has black screen casting doesn't work on both chrome and firefox
