### ISSUE TITLE
Frequent disconnects

### ISSUE THREAD

**Issue by GigaFyde** [nurdism/neko#22]
I found this project today, and so far it is exactly what me and my friends have been looking for.
With the exception that we lose the connection from time to time.

Any solution?

I run the docker behind a nginx reverse proxy through cloudflare.

**Comment by nurdism** [comment]
post your client and server logs

**Comment by GigaFyde** [comment]
Hiya, I did some looking into the disconnects, and after configuring my reverse proxy some more, the disconnects have disappeared.

Apologies for the inconvienience and keep up the absolutely amazing work!
