### ISSUE TITLE
Fresh install - timeout

### ISSUE THREAD

**Issue by Cupcake911** [nurdism/neko#23]
Making a fresh install using the provided instructions results in neko running, but when trying to log in, you get a time out error.

**Comment by nurdism** [comment]
post your client/server logs

**Comment by Cupcake911** [comment]
Where can I find them? I have no big knowledge of docker.

**Comment by nurdism** [comment]
for the client logs, they are located in the browser (ctrl+shift+i) for the server logs run `sudo docker run -p 8080:8080 -e NEKO_PASSWORD='secret' -e NEKO_ADMIN='secret' --shm-size=1gb nurdism/neko:latest ` and copy the console output

**Comment by Cupcake911** [comment]
Here we go, thank you for explaining where to find the logs!

[server.log](https://github.com/nurdism/neko/files/4123582/server.log)
[client.log](https://github.com/nurdism/neko/files/4123583/client.log)

**Comment by nurdism** [comment]
what browser are you using @Cupcake911

**Comment by Cupcake911** [comment]
Firefox, latest version. Could it be because of add-ons like ublock origin?

**Comment by nurdism** [comment]
I'm seeing `ReferenceError: RTCPeerConnection is not defined` which means your browser has no webrtc support or its being blocked somehow. Are you on Linux desktop?

**Comment by Cupcake911** [comment]
No, but now that you mention it, I remember I blocked webrtc some time ago. I just tested it on a different browser and it's working. What a simple solution... sorry for bothering. But thank you very much, I very much appreciate your support and engagement as developer!

**Comment by nurdism** [comment]
Awesome glad that worked out for you, thanks for the kind words
