### ISSUE TITLE
[BUG] Can't Type as Client in Firefox

### ISSUE THREAD

**Issue by CorySanin** [nurdism/neko#26]
**Describe the bug**
Perhaps there is something I'm missing, but I'm unable to type anything into the browser through the client running inside of Firefox. Client works fine in Chrome.

**To Reproduce**
1. Start docker container (nurdism/neko:firefox)
2. Open the web client within Firefox
3. Take control of the remote
4. Attempt to type anything

**Expected behavior**
Can type into the remote browser when control is obtained

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows, Manjaro
 - Browser: Firefox
 - Version: 72.0.2 for both OS's

**Additional context**
I tried using Chrome on Windows and it worked as expected. Still using Firefox within the container

**Client Log:**
I see this a bunch:
```
TypeError: "navigator.clipboard.readText is not a function"
```

**Server Log:**
N/A

**Comment by Rami-Pastrami** [comment]
had a similar issue through a nginx reverse proxy only. It went away randomly though

**Comment by CorySanin** [comment]
That might be the issue then. I'm also using nginx as a reverse proxy.

**Comment by nurdism** [comment]
This might be due to firefox and needing https for clipboard access, I need to do some testing on firefox with https.

**Comment by CorySanin** [comment]
Do you think that if I use Chrome in the container and Firefox for the client that my setup would work?

**Comment by nurdism** [comment]
well `navigator.clipboard.readText` is a client side issue, the server should be working.

**Comment by nurdism** [comment]
so can confirm, does not work on ff, chrome works just fine. going to look into alternative for  `clipboard` api on ff

https://i.imgur.com/FnkGCzw.png

**Comment by nurdism** [comment]
I've updated the docker container with a potential fix for this, please update and check it out. Reopen if this still an issue for you

**Comment by CorySanin** [comment]
Thanks, that works!
