### ISSUE TITLE
cannot assign requested address

### ISSUE THREAD

**Issue by danielpmc** [nurdism/neko#30]
While connecting i get this error
neko_1  |
neko_1  | 2020-02-08 22:53:48,484 DEBG 'neko' stdout output:
neko_1  | 10:53PM WRN could not get server reflexive address udp6 stun:stun.l.google.com:19302: write udp6 [::]:59037->[2a00:1450:400c:c06::7f]:19302: sendto: cannot assign requested address
neko_1  |  module=webrtc subsystem=ice
neko_1  |
neko_1  | 2020-02-08 22:53:48,484 DEBG 'neko' stdout output:
neko_1  | 10:53PM INF signaling state changed to have-remote-offer module=webrtc subsystem=pc
neko_1  |
neko_1  | 2020-02-08 22:53:48,490 DEBG 'neko' stdout output:
neko_1  | 10:53PM DBG Started agent: isControlling? false, remoteUfrag: "9gzY", remotePwd: "Zy44o6PTAImATzH2E8NP/I/e" module=webrtc subsystem=ice
neko_1  | 10:53PM INF Setting new connection state: Checking module=webrtc subsystem=ice
neko_1  |
neko_1  | 2020-02-08 22:53:48,603 DEBG 'neko' stdout output:
neko_1  | 10:53PM INF ICE connection state changed: checking module=webrtc subsystem=pc
neko_1  |
neko_1  | 2020-02-08 22:53:48,611 DEBG 'neko' stdout output:
neko_1  | 10:53PM INF signaling state changed to stable module=webrtc subsystem=pc
neko_1  |
neko_1  | 2020-02-08 22:53:58,490 DEBG 'neko' stdout output:
neko_1  | 10:53PM INF Setting new connection state: Failed module=webrtc subsystem=ice
neko_1  | 10:53PM INF ICE connection state changed: failed module=webrtc subsystem=pc
neko_1  | 10:53PM INF peer connection state changed: failed module=webrtc subsystem=pc
neko_1  |
neko_1  | 2020-02-08 22:53:58,490 DEBG 'neko' stdout output:
neko_1  | 10:53PM INF peer disconnected id=ICwd6dKMVHStvbxlSwCRlAhMPBwl9scy module=webrtc
neko_1  | 10:53PM DBG read message error error="read tcp 172.18.0.2:8080->192.168.0.2:62611: use of closed network connection" module=websocket
neko_1  | 10:53PM DBG handle socket ending address=192.168.0.2:62611 module=websocket
neko_1  |
neko_1  | 2020-02-08 22:53:58,491 DEBG 'neko' stdout output:
neko_1  | 10:53PM DBG session destroyed id=ICwd6dKMVHStvbxlSwCRlAhMPBwl9scy module=webrtc
neko_1  | 10:53PM DBG session destroyed id=ICwd6dKMVHStvbxlSwCRlAhMPBwl9scy module=websocket
neko_1  | 10:53PM DBG session ended address=192.168.0.2:62611 module=websocket session=ICwd6dKMVHStvbxlSwCRlAhMPBwl9scy
neko_1  | 10:53PM DBG request complete (0) module=http req={"agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","method":"GET","proto":"HTTP/1.1","remote":"192.168.0.2:62611","scheme":"http","uri":"http://192.168.0.51/ws?password=neko"} res={"bytes":0,"elapsed":10255.521863,"status":0,"time":"Sat, 08 Feb 2020 22:53:58 UTC"}
neko_1  | 10:53PM DBG session destroyed id=ICwd6dKMVHStvbxlSwCRlAhMPBwl9scy module=webrtc
neko_1  |
neko_1  | 2020-02-08 22:53:58,491 DEBG 'neko' stdout output:
neko_1  | 10:53PM DBG session destroyed id=ICwd6dKMVHStvbxlSwCRlAhMPBwl9scy module=websocket
neko_1  |
neko_1  | 2020-02-08 22:54:03,823 DEBG 'neko' stdout output:
neko_1  | 10:54PM DBG request complete (200) module=http req={"agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","method":"GET","proto":"HTTP/1.1","remote":"192.168.0.2:62608","scheme":"http","uri":"http://192.168.0.51/fonts/whitney-600.be0060da.woff"} res={"bytes":82688,"elapsed":8.782967,"status":200,"time":"Sat, 08 Feb 2020 22:54:03 UTC"}
neko_1  |

How would i fix?

**Comment by sad** [comment]
I believe this is related to #25.

**Comment by nurdism** [comment]
this is indeed related to #25
