### ISSUE TITLE
Virtual machine cursor doesn't sync with computer mouse.

### ISSUE THREAD

**Issue by RW456** [nurdism/neko#33]
When I ran docker compose, it worked, except for one thing. The virtual machine's mouse won't sync with mine. I can see the virtual machine, I just can't control it. This is the only error in the console

`DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`

This is what comes before the console error.

`[NEKO] DBG received websocket event member/list with payload:  Object`

This is my config file: (Changed the port due to 80 being used by apache web server)

'version: "2.0"
services:
  neko:
    image: nurdism/neko:firefox
    restart: always
    shm_size: "4gb"
    ports:
      - "90:8080"
      - "59000-59100:59000-59100/udp"
    environment:
      DISPLAY: :99.0
      NEKO_PASSWORD: neko
      NEKO_ADMIN: admin
      NEKO_BIND: :8080'

Is this an actual bug, or am I just doing something wrong?

**Comment by nurdism** [comment]
Its a bug, seems if an error gets thrown it will stop the required events from fireing, a quick workaround for this is to click on the page when it is loading. I'll be making a fix for this soon
