### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by TiredSysOp** [nurdism/neko#34]
**Is your feature request related to a problem? Please describe.**
I don't know if I've done something wrong but the locale for firefox and chrome always reverts to United Arab Emirates, regardless of what's set on the host system, in the docker compose file or in the browser within neko

**Describe the solution you'd like**
I would like the ability to change the locale, this would be a useful feature as neko is "usually" installed on a vps. Either through the compose file, as a flag when run through docker or within neko.

**Additional context**
Using the latest docker image and followed instructions from the official site, I don't think it's a geoip issue as the ip my vps uses is in germany according to maxmind

**Comment by nurdism** [comment]
I ran into the same issue, its a google thing https://www.reddit.com/r/google/comments/3trv4t/google_thinks_im_in_the_uae/ google is useing an out dated ip database. You have to manually set it in the google settings.
