### ISSUE TITLE
Would it be possible also to run anything another then a Webbrowser like a Software?

### ISSUE THREAD

**Issue by LavaMensch** [nurdism/neko#36]
Could this be used for an thinfinity virtualui alternative?

**Comment by nurdism** [comment]
yes, like this https://github.com/nurdism/neko/blob/master/.docker/files/chromium/Dockerfile use nurdism/neko:base and add a supervisord conf file to /etc/neko/supervisord/ folder

**Comment by LavaMensch** [comment]
Would it be also available for exe files? So that i can virtualize Windows Programms?

**Comment by nurdism** [comment]
Unfortunately no this is Linux only
