### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by danielpmc** [nurdism/neko#38]
Hello,

What upload/download speed does Neko need/use? 

Would it be possible to make a stripped down version of just the web browser to use for another project? 

Is there anyway to change what preinstaleld extensions the web browser(s) come with? 

Thanks,
Dan

**Comment by nurdism** [comment]
**What upload/download speed does Neko need/use?**
I'm not sure haven't tested it at all. 

**Would it be possible to make a stripped down version of just the web browser to use for another project?**
**Is there anyway to change what preinstaleld extensions the web browser(s) come with?**
yes and yes, you can use `nurdism/neko:base` and make your own docker image all you need to do is install your app and add a supervisord config in `/etc/neko/supervisord/` you can look at https://github.com/nurdism/neko/tree/master/.docker/files/chromium for reference

**Comment by GigaFyde** [comment]
The average outgoing bitrate per user seems to be ~3.4 mbps at a 720p 60fps stream
