### ISSUE TITLE
Can this project run on Heroku

### ISSUE THREAD

**Issue by TheFatalKiller** [nurdism/neko#41]
Hey, I’m wondering if there is a way to deploy this into Heroku. (https://heroku.com)

**Comment by nurdism** [comment]
I don't think this would work on Heroku. Not sure what kinda of specks Heroku offers, but I'm pretty sure it cant handle what n.eko needs (at least on the free tier) I'll leave this open for anyone who wants to attempt this.

**Comment by GigaFyde** [comment]
Due to heroku memory limitations, this would pretty much never be able to run

**Comment by TheFatalKiller** [comment]
Do you know any other free providers that would be able to run it?

**Comment by GigaFyde** [comment]
I am personally not even sure how rabb.it was able to keep proving their services for free for how long they did at all.
The resources it takes up aren't exactly lightweight, so if they had went paid they might have been able to keep afloat.

**Comment by TheFatalKiller** [comment]
I’m new to hosting something like this so something like a video guide would be helpful xD

**Comment by sad** [comment]
@TheFatalKiller [DigitalOcean](https://www.digitalocean.com/) is currently offering $100 in credit (and their VMs are billed hourly) to new users. You could also try [Vultr](https://www.vultr.com/promo/try50/?service=try50&gclid=EAIaIQobChMIwt3XyZmk6AIV04TVCh10yQFZEAAYASAAEgIZWvD_BwE) who are giving away $50 in credit to new users. Either of these will be fine.
