### ISSUE TITLE
[BUG] Cannot lock/unlock the room as admin

### ISSUE THREAD

**Issue by tscs37** [nurdism/neko#44]
**Describe the bug**
I'm unable to lock or unlock the room after entering admin credentials, the button in question is disabled (I double checked and I entered the admin credentials, they are the only creds that have been setup)

**To Reproduce**
1. Install neko as per docker-compose.yml (Firefox Version)
2. Try to unlock the room (button is disabled/non-functional)

**Expected behavior**
Clicking on the lock icon unlocks the room for others to use

**Desktop (please complete the following information):**
- OS: Linux
- Browser: Chromium/Firefox

**Comment by nurdism** [comment]
when you are logged in do you see this 

![img](https://i.imgur.com/DaITpGA.png)

if you do not, that means you are not logged in as an admin

**Comment by tscs37** [comment]
No, I don't see this; 
![Selection_408](https://user-images.githubusercontent.com/1774339/76726470-7fa8c400-6751-11ea-8d34-b2ecf9a1281d.png)

This is what I see after logging in as administrator from a clean docker setup.

**Comment by nurdism** [comment]
see my answer in #45
