### ISSUE TITLE
Other Users

### ISSUE THREAD

**Issue by TheOnlyBread** [nurdism/neko#45]
Is there any way to add any other users other than the admin ?

**Comment by TiredSysOp** [comment]
environment:
      DISPLAY: :99.0
      NEKO_PASSWORD: neko <-- this password is used for standard users
      NEKO_ADMIN: admin
      NEKO_BIND: :8080

**Comment by nurdism** [comment]
`NEKO_PASSWORD` and `NEKO_ADMIN` are just passwords, you can have *any* username, as long as you have the password. If you use the `NEKO_ADMIN` password you will be an admin when you login, if you use the `NEKO_PASSWORD` you will be a normal user
