### ISSUE TITLE
[BUG] Confusing wording re: "username" on login page

### ISSUE THREAD

**Issue by hendersonreed** [nurdism/neko#52]
**Describe the bug**

This may just be an opinion, but I think to use the term "username" on the login page is confusing when the application is stateless and doesn't have accounts. This initially confused me as I looked for documentation on creating user accounts. I also think it makes it harder for new users who might be given a link to Neko without explanation that the username field can be whatever they choose.

**Expected behavior**

Instead, I would propose that we change the login page and internal code relating to the username to use the term "nick" or "display name", unless a roadmap some place includes adding discrete user accounts in the future.

I'd be happy to make a PR myself - I'm not familiar with Vue, but I have a little Javascript experience and figure I could work it out.

**Comment by nurdism** [comment]
Changing it to display name is a great idea

**Comment by hendersonreed** [comment]
Cool, I'll make a PR - can't guarantee when I'll have it done. Any idea on if it will be simple as just a search and replace on the whole codebase?

**Comment by GigaFyde** [comment]
Personally I would only change the login box to not unnecessarily break the rest of the codebase.

**Comment by hendersonreed** [comment]
Ah, OK! That's reasonable enough then, I can get that done for sure, even with my limited Javascript knowledge :) Thanks, I'll get the PR to you in a bit.

**Comment by GigaFyde** [comment]
The file you're looking for is `client/src/components/connect.vue`

**Comment by nurdism** [comment]
9c6fd96
