### ISSUE TITLE
[ISSUE] Hosting multiple copies on the same machine

### ISSUE THREAD

**Issue by GigaFyde** [nurdism/neko#56]
Been trying to get multiple rooms working.
All seems well in terms of connectivity, except I can't seem to get a display output on the second room.

**Comment by GigaFyde** [comment]
This is getting more and more interesting,
I'm able to control the first room's cursor from the second room.

**Comment by TiredSysOp** [comment]
@GigaFyde Might be a nice feature from an administration stand point

**Comment by GigaFyde** [comment]
Well it could be if indended :P

**Comment by nurdism** [comment]
have you changed the `NEKO_EPR: "59000-59100"` for each contianer? https://github.com/nurdism/neko/blob/master/server/internal/types/config/webrtc.go#L55

**Comment by GigaFyde** [comment]
I have indeed tried that.

**Comment by GigaFyde** [comment]
Fix supplied by @m1k1o in #49
