### ISSUE TITLE
I want to make a mobile app for this.

### ISSUE THREAD

**Issue by RW456** [nurdism/neko#58]
I want to make myself a mobile app for this, as I think it would be helpful. However, the code on this is minified, so I'm having trouble working with the APIs. Is there a non minified version somewhere, so I can actual decipher this code?

**Comment by nurdism** [comment]
None of the code is minified? Only when packaged it gets minified

**Comment by RW456** [comment]
Oh, sorry. I was only using the console in the browser, not the actual source code
