### ISSUE TITLE
[BUG] Secure connection not working

### ISSUE THREAD

**Issue by SweetLouHD** [nurdism/neko#61]
Browsers kept complaining about entering password for Plex and Netflix because the site wasn't secure. I enabled https on the Wamp/Apache server hosting the client, but when I try connecting from the secure site it won't join the server. Is there something missing from my docker config that would prevent the secure connection?

`[NEKO] DBG connecting to wss://neko.server.site:8081/ws?password=neko`
`WebSocket connection to 'wss://neko.server.site:8081/ws?password=neko' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`
I have changed out the actual URL in the above console log as I am not ready for this site to be publicly used yet.

I switched over to using the docker compose again
`
version: '3.4'
services:
  neko1:
    image: nurdism/neko:firefox
    container_name: neko1
    restart: unless-stopped
    shm_size: "4gb"
    environment:
      DISPLAY: :99.0
      NEKO_EPR: E678-E6DB
    ports:
      - "8081:8080"
      - "59000-59099:59000-59099/udp"

  neko2:
    image: nurdism/neko:firefox
    container_name: neko2
    restart: unless-stopped
    shm_size: "4gb"
    environment:
      DISPLAY: :99.0
      NEKO_EPR: E6DC-E73F
    ports:
      - "8082:8080"
      - "59100-59199:59100-59199/udp"

  neko3:
    image: nurdism/neko:firefox
    container_name: neko3
    restart: unless-stopped
    shm_size: "4gb"
    environment:
      DISPLAY: :99.0
      NEKO_EPR: E740-E7A3
    ports:
      - "8083:8080"
      - "59200-59299:59200-59299/udp"

`

**Comment by GigaFyde** [comment]
I experience no issues using a nginx reverse proxy, so this seem due to your hosting configuration.

**Comment by nurdism** [comment]
to setup ssl you need to have a valid ssl cert generated for your host. Please provide some more info than "not working". 

Your config looks right, but it does not include any setup need for ssl, I honestly haven tried neko with ssl so no idea if it'll work right out of the box, I've been using reverse proxies for ssl
