### ISSUE TITLE
[FEATURE] i18n keyboard layouts

### ISSUE THREAD

**Issue by m1k1o** [nurdism/neko#72]
Ony US (standard) layout is supported. It would be great, to choose cusom layout or even (if possible) get this information from host browser.

When I am using any other layout, it does not bind correclty. I am not expecting it, to bind correctly that chosen layout (since it is not implemented yet) but not even US layout works, when I have any different on my host computer.

E.G. Slovakian keyboard bind correctly except key `-` is switched with `/` (and ofc this is quertz, so `z` is switched with `y` what is expected). On german keyboard layout are more keys (5+) switched. So only if i switch my host to US keyboard is neko usable.

Since i18n was introduced, this would be also great feature.

**Comment by nurdism** [comment]
this would need a rewrite on how the keybord input is handled on both server and client

**Comment by nurdism** [comment]
maybe handle it like guacamole https://github.com/apache/guacamole-client/blob/master/guacamole-common-js/src/main/webapp/modules/Keyboard.js

**Comment by m1k1o** [comment]
WIP https://github.com/m1k1o/neko/commit/aa1fedcb24a85ba9eadd79031bbc25f498a4fdf3

**Comment by m1k1o** [comment]
Implemented handling from guacamole. https://github.com/nurdism/neko/compare/ca0b5b2d354c938859680f93caac1b5c1279b2ff...m1k1o:5cf9c2931922e5912fee06c0661f5dcf0726c7df
