### ISSUE TITLE
[Question] set video resolution?

### ISSUE THREAD

**Issue by innerop** [nurdism/neko#83]
Hello @nurdism ,

Can we force a resolution higher than 1280x720, assuming you have enough cores and bandwidth?

**Comment by m1k1o** [comment]
Hi,

log in as admin and you can choose up to Full HD.

![image](https://user-images.githubusercontent.com/7534274/80844854-06cdd080-8c08-11ea-81e8-9501510c9ef1.png)

**Comment by innerop** [comment]
Nice! Thanks.
