### ISSUE TITLE
[BUG] Issues with screen size

### ISSUE THREAD

**Issue by m1k1o** [nurdism/neko#90]
Default screen size is changed everytime when stream starts, so when first user joins room.

https://github.com/nurdism/neko/blob/ca0b5b2d354c938859680f93caac1b5c1279b2ff/server/internal/remote/manager.go#L103-L109

Meaning, when I change screen size to `1920x1080@30` and everyone leaves room, when I then join it's reset.

Since screen size is updated when **first user joins**, if last screen size was different from current, browser size remains, only stream size changes. This can cause black bars and not maximized browser.

* Is this intended?
* Shouldn't be this setting persistent?

![image](https://user-images.githubusercontent.com/7534274/84581166-81306980-adde-11ea-9804-1ac4ab08aa77.png)

Another problem is, cursor mapping is using **old screen size**, so cursor is not exactly mapped to hosts cursor.

**Because screen size update is sent *before* screen change happens.**

https://github.com/nurdism/neko/blob/ca0b5b2d354c938859680f93caac1b5c1279b2ff/server/internal/websocket/session.go#L15-L18

Default screen size appears to be `1920x1080`, meaning on very first join user gets desired default size `1280x720@30` but tells user, that `1920x1080` is used.

If screen size is not manipulated, only first joined user is affected. After refresh it works.

**Comment by nurdism** [comment]
I think this was fixed? (if not reopen)

**Comment by m1k1o** [comment]
@nurdism that bug ist fixed. but screen size is not persistent. so when everyone leaves, it will be reset. question was, whether this was intended behavior or bug.

**Comment by nurdism** [comment]
ahh ok I see, intended behavior was to have the screen revert back to default screen size when the room is empty.
