### ISSUE TITLE
[Feature Request] Add Neko variant using custom Chromium build from Woolyss

### ISSUE THREAD

**Issue by ghost** [nurdism/neko#98]
**Is your feature request related to a problem? Please describe.**
If a user wants to watch a media file that has been encoded in HEVC/x265 in the currently available builds of Neko, the video playback will either outright fail or cause the origin server to first transcode the video before serving it, a process which greatly reduces the quality of the video. HEVC is burdened by its patents and licensing fees which is why [it currently isn't supported](https://caniuse.com/#search=hevc) by the two big browsers Firefox and Chrome and likely never will be.

**Describe the solution you'd like**
Since Chrome is based on the open-source project Chromium, people have developed custom variants of the latter with support for HEVC/x265. These are available for all major platforms, including Linux, and can be downloaded on [Woolyss'](https://chromium.woolyss.com/) website. The build that would have be used for Neko is [this one](https://github.com/macchrome/linchrome/releases/download/v83.0.4103.116-r756066-portable-ungoogled-Lin64/ungoogled-chromium_83.0.4103.116_1.vaapi_linux.tar.xz) (since it is marked with `all-codecs+`).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by m1k1o** [comment]
You can create your own Dockerfile `FROM nurdism/neko:openbox` and install this.

This is Chomium dockerfile:
https://github.com/nurdism/neko/blob/395e23a15562e54a70ce82b2c140ef9c81c9b249/.docker/files/chromium/Dockerfile#L1-L25

I would looking forward to see H265 support in neko!

**Comment by ghost** [comment]
@m1k1o Thanks for the pointer, but it looks like some of the required libraries (e.g. libva2) are only available on Debian Buster and newer. This means that Neko's entire image chain (deps -> base -> openbox -> chromium) needs to be updated from Stretch to Buster for this change.

**Comment by m1k1o** [comment]
I did it already in my fork. Check it out. @whalehub

**Comment by whalehub** [comment]
@m1k1o It shows me that it's also based on `stretch-slim`: https://github.com/m1k1o/neko/blob/dev/.docker/files/deps/Dockerfile

**Comment by ghost** [comment]
@m1k1o Ah, thank you. I'll start working on implementing support for the custom Chromium build based on your fork then.

**Comment by nurdism** [comment]
I'm only running stretch because of the space savings (is not that much compared to Buster) @m1k1o if all the images work fine I don't mind changing to buster

**Comment by ghost** [comment]
@m1k1o I'm happy to report that I just finished implementing this feature request and that the custom Chromium build can indeed Direct Play both 8-bit and 10-bit HEVC content. I'll open a pull request on your repo once I've ironed out a bug where Chromium doesn't start with a maximized window even when using the `--start-maximized` runtime flag. While it can still be maximized by clicking on the corresponding button, I'd prefer to have it work like the original Neko.

![Chromium](https://xbb.datahoarder.dev/VUSu3/koWiMiLo07.png/raw)

**Comment by m1k1o** [comment]
@nurdism buster works for me great. I created completly new workflow in my custom folder (didn't touch your old ones) hecne pull request from my fork would not be possible. Either you modify your dockerfiles according to mine or they would be completly replaced.

@whalehub i faced similar issue, where browser didn't start maximized. It was caused by missing openbox or bad window identifier.

https://github.com/m1k1o/neko/blob/aed37c553fc1221661a332787adb54d848fc8237/.m1k1o/chromium/openbox.xml#L16-L21

**Comment by ghost** [comment]
@m1k1o Bingo, that was it. I changed it from `chromium-browser` to `chromium-devel` and now it works as expected. I just opened a pull request on your repo. 👍

@alectrocute If you want to give this custom build a spin, feel free to use `graywhale/neko:chromium`. It's a drop-in replacement for the official Neko Chromium image, so it requires the same parameters, see https://n.eko.moe/#/docker.

**Comment by m1k1o** [comment]
@whalehub just tried it, works great. Thanks!
